name: event_management
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  freezed_annotation: ^3.1.0
  go_router: ^16.2.4
  json_annotation: ^4.9.0
  logger: ^2.6.1
  package_info_plus: ^9.0.0
  retrofit: ^4.7.3
  riverpod_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.7.1
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  retrofit_generator: ^10.0.0
  riverpod_generator: ^3.0.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
