// Mocks generated by Mockito 5.4.6 from annotations
// in event_management/test/features/auth/presentation/bloc/login_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:event_management/features/auth/data/models/change_password_request_dto.dart'
    as _i7;
import 'package:event_management/features/auth/data/models/register_request_dto.dart'
    as _i5;
import 'package:event_management/features/auth/data/models/reset_password_dto.dart'
    as _i8;
import 'package:event_management/features/auth/data/models/user_response_dto.dart'
    as _i2;
import 'package:event_management/features/auth/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserResponseDto_0 extends _i1.SmartFake
    implements _i2.UserResponseDto {
  _FakeUserResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> login({required String? email, required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> register(_i5.RegisterRequestDto? registerRequestDto) =>
      (super.noSuchMethod(
            Invocation.method(#register, [registerRequestDto]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#register, [registerRequestDto]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> changePassword(
    _i7.ChangePasswordRequestDto? changePasswordRequestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [changePasswordRequestDto]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#changePassword, [changePasswordRequestDto]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#forgotPassword, [email]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> resetPassword(_i8.ResetPasswordDto? resetPasswordDto) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [resetPasswordDto]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#resetPassword, [resetPasswordDto]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i2.UserResponseDto> getAuthUser() =>
      (super.noSuchMethod(
            Invocation.method(#getAuthUser, []),
            returnValue: _i4.Future<_i2.UserResponseDto>.value(
              _FakeUserResponseDto_0(this, Invocation.method(#getAuthUser, [])),
            ),
          )
          as _i4.Future<_i2.UserResponseDto>);

  @override
  _i4.Future<void> saveCredentialsForBiometric({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveCredentialsForBiometric, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, String>?> getSavedCredentialsForBiometric() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedCredentialsForBiometric, []),
            returnValue: _i4.Future<Map<String, String>?>.value(),
          )
          as _i4.Future<Map<String, String>?>);

  @override
  _i4.Future<void> clearSavedCredentialsForBiometric() =>
      (super.noSuchMethod(
            Invocation.method(#clearSavedCredentialsForBiometric, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
